# Site settings
title: ALo - Personal Page
description: A look into the mind of Albert Lo
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "lohoi.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Albert Lo
user_description: Hi, my name is Albert and I'm a full-time Software Engineer at Qualtrics working on the Reporting Platform team. I build software to help companies improve their product by drawing impactful insights from customers. When I'm not closing the experience gap or writing code, you can find me reading books about the economy or behavioral psychology. 
email: lohoi@umich.edu
# twitter_username: lorem_ipsum
# github_username:  lohoi
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
